Repository pika-org/pika, pull requests merged in 2022-08, with the labels that each got.

#344 Update the stream attribute in `cusolver_handle::set_stream`
  libs/pika/async_cuda/src/cusolver_handle.cpp
Labels: type: bug

#394 Move `SPACK_USER_CACHE_PATH` to Jenkins' scratch directory
  .jenkins/cscs/env-common.sh
Labels: category: spack

#400 Clean up type support part 2
  libs/pika/algorithms/include/pika/parallel/algorithms/fill.hpp
  libs/pika/algorithms/include/pika/parallel/algorithms/for_loop.hpp
  libs/pika/algorithms/include/pika/parallel/algorithms/nth_element.hpp
  libs/pika/algorithms/include/pika/parallel/algorithms/sort.hpp
  libs/pika/algorithms/include/pika/parallel/algorithms/stable_sort.hpp
  libs/pika/algorithms/include/pika/parallel/algorithms/uninitialized_default_construct.hpp
  libs/pika/algorithms/include/pika/parallel/algorithms/uninitialized_fill.hpp
  libs/pika/algorithms/include/pika/parallel/algorithms/uninitialized_value_construct.hpp
  libs/pika/algorithms/include/pika/parallel/util/partitioner.hpp
  libs/pika/async_combinators/include/pika/async_combinators/wait_all.hpp
  libs/pika/async_combinators/include/pika/async_combinators/when_each.hpp
  libs/pika/execution/include/pika/execution/algorithms/detail/predicates.hpp
  libs/pika/execution/include/pika/execution/algorithms/ensure_started.hpp
  libs/pika/execution/include/pika/execution/algorithms/let_error.hpp
  libs/pika/execution/include/pika/execution/algorithms/let_value.hpp
  libs/pika/execution/include/pika/execution/algorithms/make_future.hpp
  libs/pika/execution/include/pika/execution/algorithms/schedule_from.hpp
  libs/pika/execution/include/pika/execution/algorithms/split.hpp
  libs/pika/execution/include/pika/execution/algorithms/when_all_vector.hpp
  libs/pika/execution/include/pika/execution/executors/execution.hpp
  libs/pika/execution/include/pika/execution/executors/execution_parameters.hpp
  libs/pika/execution/include/pika/execution/executors/execution_parameters_fwd.hpp
  libs/pika/execution/include/pika/execution/traits/executor_traits.hpp
  libs/pika/execution/include/pika/execution/traits/future_then_result_exec.hpp
  libs/pika/execution_base/include/pika/execution_base/sender.hpp
  libs/pika/functional/include/pika/functional/bind.hpp
  libs/pika/functional/include/pika/functional/bind_back.hpp
  libs/pika/functional/include/pika/functional/deferred_call.hpp
  libs/pika/functional/include/pika/functional/invoke.hpp
  libs/pika/functional/include/pika/functional/invoke_fused.hpp
  libs/pika/futures/include/pika/futures/future.hpp
  libs/pika/futures/include/pika/futures/traits/future_then_result.hpp
  libs/pika/iterator_support/include/pika/iterator_support/boost_iterator_categories.hpp
  libs/pika/iterator_support/include/pika/iterator_support/counting_iterator.hpp
  libs/pika/iterator_support/include/pika/iterator_support/iterator_adaptor.hpp
  libs/pika/iterator_support/include/pika/iterator_support/traits/is_iterator.hpp
  libs/pika/iterator_support/include/pika/iterator_support/traits/is_sentinel_for.hpp
  libs/pika/iterator_support/include/pika/iterator_support/transform_iterator.hpp
  libs/pika/iterator_support/tests/unit/is_iterator.cpp
  libs/pika/pack_traversal/include/pika/pack_traversal/detail/pack_traversal_async_impl.hpp
  libs/pika/pack_traversal/include/pika/pack_traversal/detail/pack_traversal_impl.hpp
  libs/pika/threading_base/include/pika/threading_base/annotated_function.hpp
  libs/pika/type_support/include/pika/type_support/decay.hpp
  libs/pika/type_support/include/pika/type_support/detail/with_result_of.hpp
  libs/pika/type_support/include/pika/type_support/detail/wrap_int.hpp
  libs/pika/type_support/include/pika/type_support/detected.hpp
  libs/pika/type_support/include/pika/type_support/empty_function.hpp
  libs/pika/type_support/include/pika/type_support/equality.hpp
  libs/pika/type_support/include/pika/type_support/lazy_conditional.hpp
  libs/pika/type_support/include/pika/type_support/void_guard.hpp
Labels: type: cleanup

#404 Test all `async_cuda` tests on HIP CI
  .jenkins/cscs-ault/ctest.cmake
Labels: category: CI

#422 Set spack user config and cache path only if not set
  .jenkins/cscs-ault/env-common.sh
  .jenkins/cscs/env-common.sh
Labels: category: CI
